### ISSUE TITLE
Considering creating ListT

### ISSUE THREAD

**Issue by leandrob13** [typelevel/cats#977]
I am currently working on a project and I find myself needing the ListT abstraction. I read in [#766](https://github.com/typelevel/cats/issues/766) that there was some issues with consistency, also that you were considering adding the transformers to a separate project. The question is: should I start working on ListT or there is some sort of objection about this ADT?

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz/issues/921

**Comment by leandrob13** [comment]
@xuwei-k I have checked the alternative https://wiki.haskell.org/ListT_done_right and saw the problem you posted here https://github.com/scalaz/scalaz/issues/921. I checked the implementation of scalaz StreamT as suggested in the gitter channel and found out that it is done with the same principle as in the haskell wiki post. I am not ready to give up on this so I am working on a similar implementation for List instead of a Stream. I got a basic version working and it passes the kleisli associativity test you showed on the scalaz issue. I am using StreamT implementation as a base for this. 

Any objections to this idea?

**Comment by xuwei-k** [comment]
I implemented the same thing before. It satisfy laws. IIRC it is hard to use because not stack-safe.

**Comment by leandrob13** [comment]
Should we work on doing it safe then? http://functorial.com/stack-safety-for-free/index.pdf
Maybe we could use Trampoline or the equivalent MonadRec for Cats?

**Comment by fommil** [comment]
I was also surprised that this did not exist when writing https://leanpub.com/fp-scala-mortals/

I seen the Haskell reference to "done right" and it seems that this is possible.

I have also struggled to understand to understand the Haskell examples in the context of Scala `for` comprehensions. Sure the monad laws may be broken by a naive `ListT` (and I still don't fully understand why), but I don't see why it would be unsafe to use even a naive `ListT` in a `for` comprehension... it doesn't assume or make use of associativity as far as I am aware. Should we therefore have a lesser class of "flatmap transformers"?

**Comment by ceedubs** [comment]
I'm going to close this out now that we have https://typelevel.org/cats/faq.html#listt documented. I think that `Nested` scratches most of the `ListT` itches without the `ListT` issues.
